#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check ESLint Standards
npm run check-lint ||
(
echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
   ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
   false; 
)



# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... ✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'

